src/views/feed/AkoStampWriteView.vue, src/views/mainpage/MainpageView.vue
- [ x] Feature
issue를 통한 브랜치 테스트 연습용 pr입니다
- 메인페이지 svg 를 img로 넣었습니다
- 내용을 적어주세요.
=> [Feat] 메인페이지 이미지 수정 및 브랜치 테스트

src/components/layout/Footer.vue, src/main.js, src/views/calendar/CalendarMainView.vue, src/views/mainpage/MainpageView.vue
Footer 라우터 절대 경로로 수정 및 메인페이지 캘린더 페이지 개발
- Footer.vue 라우터 절대경로로 변경하여 페이지간 이동시 오류 나지 않도록 수정(아코폴리오는 아직 연결 안됨, 피드 페이지는 임시로 board로 연결 했습니다)
- 메인페이지 테스트 스탬프를 svg 파일로 변경(크기 수정 필요)
- 캘린더 페이지 데이터 연결 테스트
- 내용을 적어주세요.
=> [Feat] Footer 라우터 절대 경로로 수정 및 메인페이지 캘린더 페이지 개발

src/views/calendar/CalendarMainScript.js, src/views/feed/MainFeedPage.vue
캘린더 임시 데이터 추가 및 피드페이지 간격 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feature] 캘린더 임시 데이터 추가 및 피드페이지 간격 수정

src/components/layout/Footer.vue, src/components/layout/PortfolioLayout.vue, src/router/index.js, src/views/akopolio/akopolioMain.vue, src/views/login/mypage/MypageView.vue
Footer.vue 에서 아코폴리오 페이지 연결되도록 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Fix] #26 - Footer.vue 에서 아코폴리오 페이지 연결되도록 수정

src/store/index.js, src/views/akopolio/akopolioCreate.vue, src/views/akopolio/akopolioMain.vue, src/views/akopolio/paginationNav.vue
아코폴리오 작성 시 목록 연동
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feature] #26 아코폴리오 작성 시 목록 연동

src/router/index.js, src/store/index.js, src/views/akopolio/akopolioCreate.vue, src/views/akopolio/akopolioDetail.vue, src/views/akopolio/akopolioMain.vue
아코폴리오 상세보기 페이지 구현
- 삭제 시 서버 연동 필요
- 수정하기 페이지 작업 필요
- 내용을 적어주세요.
=> [Feature] #26 아코폴리오 상세보기 페이지 구현

src/router/index.js, src/store/index.js, src/views/akopolio/akopolioEdit.vue
아코폴리오 수정 페이지 초안
-디자인 / 태그 수정 필요
- 내용을 적어주세요.
=> [Feature] #26 아코폴리오 수정 페이지 구현

src/views/akopolio/akopolioEdit.vue
akopolioEdit.vue 태그 기능 수정
-디자인 수정 필요
- 내용을 적어주세요.
=> [Feature] #26 -아코폴리오Edit 태그 기능 수정

.env, .github/workflows/deploy.yml, src/views/mainpage/MainpageView.vue, tailwind.config.js, vue.config.js
Tailwind CSS purge 설정 추가 및 메인페이지 백엔드 로직 작성
- Tailwind CSS
- 메인페이지 백엔드 연결 로직(퀘스트 로직 제외) 
- 내용을 적어주세요.
=> [Feat] Tailwind CSS purge 설정 추가 및 메인페이지 백엔드 로직 작성

tailwind.config.js
[Fix] Tailwind CSS 버전 오류 수정
- Tailwind 지웠다가 다시 설치했습니다
- 내용을 적어주세요.
=> [Fix] Tailwind CSS 버전 오류 수정

src/views/login/signup/SignupScript.js, src/views/login/signup/SignupView.vue
백엔드 변경에 맞추어 회원가입 vue및 js 수정
- 이메일 인증을 회원가입 버튼을 누를 때 같이 넘어가도록 변경
- 인증번호가 일치하지 않으면 인증번호 입력란 아래 표시
- 인증 확인 버튼 삭제
- 실명 name -> 백엔드 dto 확인
=> Fix: 백엔드 변경에 맞추어 회원가입 vue및 js 수정

src/views/login/signup/SignupScript.js, src/views/login/signup/SignupView.vue
- [Fix] 회원가입 페이지 실명 관련 로직 삭제
- 회원가입 시 실명을 입력받지 않도록 변경
- 내용을 적어주세요.
=> [Fix] 회원가입 페이지 실명 관련 로직 삭제

src/views/login/login/LoginScript.js, src/views/login/login/LoginView.vue, src/views/login/signup/SignupScript.js
swagger-ui를 참고하여 백엔드 배포 서버와 localhost:3000에서 로그인 회원가입 테스트를 성공하였습니다.
다만 제 이메일이 이미 가입이 돼서 회원가입 부분은 한 번 더 테스트 해야함
- 로그인 및 회원가입 .vue .js 파라미터 수정하고 함수 methods에 추가하여 연결하였습니다
- 내용을 적어주세요.
=> [Fix] 로그인 회원가입 백엔드 연동 구현

src/views/login/login/LoginScript.js, src/views/login/mypage/MypageScript.js, src/views/login/mypage/MypageView.vue, vue.config.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feat] - 마이페이지 더보기 로직 작성 및 composition api로 수정

src/main.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Fix] tailwind css 깨지는 오류 수정

tailwind.config.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: tailwind css 수정

tailwind.config.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feat] tailwind.config.js 수정

tailwind.config.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feat] css 수정

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/Edit/edit.js, src/views/akopolio/create/akopolioCreate.vue, src/views/akopolio/create/create.js, src/views/akopolio/detail/akopolioDetail.vue, src/views/akopolio/detail/detail.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feat] #26 - 백엔드 로직 및 이미지 컨테이너 생성

.env, output.css, tailwind.config.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feat] api 주소 변경

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/create/akopolioCreate.vue, src/views/akopolio/detail/akopolioDetail.vue, src/views/akopolio/main/akopolioMain.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Style] #26 - 폰트 적용

src/views/akopolio/Edit/edit.js, src/views/akopolio/create/create.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feature] #26 - 이미지 업로드 수정

src/components/common/feed/FollowStats.vue, src/components/common/feed/SearchBar.vue, src/views/feed/AkoStampFollow.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: api 연결 수정

src/views/login/login/LoginScript.js, src/views/login/login/LoginView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Fix] 마이페이지로 리다이렉트

src/views/login/login/LoginView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Fix] 로그인 페이지 치우친 오류 수정

src/views/akopolio/Edit/edit.js, src/views/akopolio/create/create.js, src/views/akopolio/detail/akopolioDetail.vue, src/views/akopolio/detail/detail.js, src/views/akopolio/main/akopolioMain.vue, src/views/akopolio/main/main.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feature] #26 - 사용자 정보 가져오기

src/router/index.js, src/views/calendar/CalendarMainScript.js, src/views/calendar/CalendarMainView.vue, src/views/mainpage/MainpageView.vue
캘린더 페이지 및 메인 페이지 퀘스트, 스탬프 받아오는 로직 작성
레벨은 임시로 아코 캐릭터 화면에 표시
- 내용을 적어주세요.
=> [Feat] #9 #21 - 캘린더 및 메인페이지 연결 로직 구현

src/router/index.js, src/views/mainpage/MainpageView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feat] 라우터에 로그인하지 않은 사용자는 다른 페이지에 접근하지 못하도록 추가

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/Edit/edit.js, src/views/akopolio/detail/akopolioDetail.vue, src/views/akopolio/detail/detail.js
내용을 적어주세요.
내용을 적어주세요.
- 내용을 적어주세요.
=> [Feature] #26 - 상세, 수정 페이지 백엔드 로직 구현

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/create/akopolioCreate.vue, src/views/akopolio/detail/akopolioDetail.vue, src/views/akopolio/main/akopolioMain.vue, src/views/akopolio/paginationNav.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [style] button div로 수정

src/store/index.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Fix] 파일 삭제 후 auth.js 모듈 오류 수정

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/Edit/edit.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feature] #26 - edit save data 로직 수정

.env
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: api 주소 변경

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/create/akopolioCreate.vue, src/views/akopolio/detail/akopolioDetail.vue, src/views/akopolio/main/akopolioMain.vue, src/views/akopolio/main/main.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Design] #26 - 디자인 수정

src/views/akopolio/main/main.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> fix: #26 예시데이터 삭제

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/create/akopolioCreate.vue, src/views/akopolio/main/akopolioMain.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> design: 디자인 수정

src/views/akopolio/main/akopolioMain.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> design: 폰트 수정

src/views/akopolio/Edit/akopolioEdit.vue, src/views/akopolio/create/akopolioCreate.vue, src/views/akopolio/main/akopolioMain.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> design: #26 디자인 수정

src/views/login/mypage/MypageScript.js, src/views/login/mypage/MypageView.vue, src/views/mainpage/MainpageView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Feat] 비밀번호 입력된 데이터가 없을 때 버튼 비활성화 분기 로직 작성

src/views/calendar/CalendarMainView.vue, src/views/login/mypage/MypageView.vue, src/views/mainpage/MainpageView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Design] 페이지 전체적인 디자인 수정

src/views/mainpage/MainpageView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Design] 메인 페이지 디자인 수정

src/views/mainpage/MainpageView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Design] 토실토실 자간 수정

src/views/mainpage/MainpageView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Design] 미니 코끼리 위치 아래로

src/views/calendar/CalendarMainView.vue, src/views/mainpage/MainpageView.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> [Design] 메인, 캘린더 페이지 디자인 수정

src/views/akopolio/detail/akopolioDetail.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> design: #26 디테일 페이지 디자인 수정
